apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sapprovedregistries
spec:
  crd:
    spec:
      names:
        kind: K8sApprovedRegistries
      validation:
        openAPIV3Schema:
          type: object
          properties:
            prefixes:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sapprovedregistries

        violation[{"msg": msg}] {
          container := input.review.object.spec.containers[_]
          not starts_with_approved_registry(container.image)
          msg := sprintf("image %q is not from an approved registry", [container.image])
        }

        starts_with_approved_registry(image) {
          prefix := input.parameters.prefixes[_]
          startswith(image, prefix)
        }
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sApprovedRegistries
metadata:
  name: dcarbn-approved-registries
spec:
  match:
    namespaces: ["dcarbn-production"]
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    prefixes:
      - ghcr.io/
