apiVersion: v1
kind: ServiceAccount
metadata:
  name: dcarbn-backend
  namespace: dcarbn
  labels:
    app.kubernetes.io/name: dcarbn-backend
    app.kubernetes.io/part-of: dcarbn-carbon-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dcarbn-frontend
  namespace: dcarbn
  labels:
    app.kubernetes.io/name: dcarbn-frontend
    app.kubernetes.io/part-of: dcarbn-carbon-platform
automountServiceAccountToken: false
