apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dcarbn-runtime-secrets
  namespace: dcarbn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: staging-secret-store
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: dcarbn/staging
        property: secret_key
    - secretKey: MFA_ENCRYPTION_KEY
      remoteRef:
        key: dcarbn/staging
        property: mfa_encryption_key
    - secretKey: DATABASE_URL
      remoteRef:
        key: dcarbn/staging
        property: database_url
    - secretKey: REDIS_URL
      remoteRef:
        key: dcarbn/staging
        property: redis_url
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: dcarbn/staging
        property: smtp_password
    - secretKey: SMTP_HOST
      remoteRef:
        key: dcarbn/staging
        property: smtp_host
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: dcarbn/staging
        property: smtp_username
    - secretKey: EMAIL_FROM_ADDRESS
      remoteRef:
        key: dcarbn/staging
        property: email_from_address
