apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: dcarbn-backend
spec:
  replicas: 2
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: dcarbn-frontend
spec:
  replicas: 2
