apiVersion: v1
kind: ConfigMap
metadata:
  name: dcarbn-backend-config
  namespace: dcarbn
data:
  FRONTEND_BASE_URL: https://standby.carbon.example.com
  CORS_ORIGINS: https://standby.carbon.example.com
  TRUSTED_HOSTS: standby.carbon.example.com
  DCARBN_REGION: secondary
