apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dcarbn-runtime-secrets
  namespace: dcarbn
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: production-standby-secret-store
