apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dcarbn-backend
  namespace: dcarbn
  labels:
    app.kubernetes.io/name: dcarbn-backend
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "Referrer-Policy: strict-origin-when-cross-origin";
spec:
  ingressClassName: nginx
  tls:
    - hosts: ["carbon.example.com"]
      secretName: dcarbn-tls
  rules:
    - host: carbon.example.com
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: dcarbn-backend-stable
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dcarbn-frontend
  namespace: dcarbn
  labels:
    app.kubernetes.io/name: dcarbn-frontend
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts: ["carbon.example.com"]
      secretName: dcarbn-tls
  rules:
    - host: carbon.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dcarbn-frontend-stable
                port:
                  name: http
