apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dcarbn-release-evidence
  namespace: dcarbn
spec:
  accessModes: ["ReadOnlyMany"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: evidence-rwx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dcarbn-supply-chain-evidence
  namespace: dcarbn
spec:
  accessModes: ["ReadOnlyMany"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: evidence-rwx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dcarbn-gitops-evidence
  namespace: dcarbn
spec:
  accessModes: ["ReadOnlyMany"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: evidence-rwx
