apiVersion: v1
kind: ConfigMap
metadata:
  name: dcarbn-backend-config
  namespace: dcarbn
data:
  FRONTEND_BASE_URL: https://carbon.example.com
  CORS_ORIGINS: https://carbon.example.com
  TRUSTED_HOSTS: carbon.example.com
  DCARBN_REGION: primary
